
package UserSetting;

import Database_Connection.DBConnection;
import Desig_info.Designation_info;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Emp_Salary_user extends javax.swing.JFrame {

    Connection con;
    
    
    
    PreparedStatement prepStmt = null;
    ResultSet res =null;
    
    SimpleDateFormat df=new SimpleDateFormat("dd-MM-yyyy");
    
    
    String SalDate="";
    java.util.Date now = new java.util.Date();
    
    
    
    public Emp_Salary_user() {
        initComponents();
        
        jDateChooser1.setDate(now);
        
        try {
            
            
            
            con=DBConnection.DBConnection();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Designation_info.class.getName()).log(Level.SEVERE, null, ex);
        } 
        try{
            String sqlSrch = "Select distinct(id) AS ID from employee_info";
            prepStmt=con.prepareStatement(sqlSrch);
            res=prepStmt.executeQuery();
            while(res.next())
            {
               
                String id=res.getString("ID");
               jComboBoxSearch.addItem(id);
               
            }
           
        }catch(SQLException e)
        {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldempname = new javax.swing.JTextField();
        jTextFieldDesig = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxSearch = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldTransportperc = new javax.swing.JTextField();
        jTextFieldgrosssalary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldHouseperc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldhouse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldmedical = new javax.swing.JTextField();
        jTextFieldMedicalperc = new javax.swing.JTextField();
        jTextFieldtransport = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldbsalary = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Employee Management System");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTextFieldSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSearch))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Designation Name :");

        jTextFieldempname.setEditable(false);
        jTextFieldempname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextFieldDesig.setEditable(false);
        jTextFieldDesig.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Employee Name :");

        jComboBoxSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBoxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID" }));
        jComboBoxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldempname, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldempname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Add New");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtondelete.setText("Delete");
        jButtondelete.setEnabled(false);
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.setEnabled(false);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRefresh)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jButtonUpdate)
                .addGap(18, 18, 18)
                .addComponent(jButtondelete)
                .addGap(18, 18, 18)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButton2)
                    .addComponent(jButtondelete)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldTransportperc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTransportperc.setText("0");
        jTextFieldTransportperc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTransportpercActionPerformed(evt);
            }
        });

        jTextFieldgrosssalary.setEditable(false);
        jTextFieldgrosssalary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldgrosssalary.setText("0");
        jTextFieldgrosssalary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldgrosssalaryMouseClicked(evt);
            }
        });
        jTextFieldgrosssalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldgrosssalaryActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Transport Allowance");

        jTextFieldHouseperc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldHouseperc.setText("0");
        jTextFieldHouseperc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHousepercActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Basic Salary :");

        jTextFieldhouse.setEditable(false);
        jTextFieldhouse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldhouse.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Medical Allowance :");

        jTextFieldmedical.setEditable(false);
        jTextFieldmedical.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldmedical.setText("0");
        jTextFieldmedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmedicalActionPerformed(evt);
            }
        });

        jTextFieldMedicalperc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldMedicalperc.setText("0");
        jTextFieldMedicalperc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMedicalpercActionPerformed(evt);
            }
        });

        jTextFieldtransport.setEditable(false);
        jTextFieldtransport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldtransport.setText("0");
        jTextFieldtransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtransportActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("House Rent :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Gross Salary :");

        jTextFieldbsalary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldbsalary.setText("0");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("%");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("%");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("%");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Payment Date");

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldtransport, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldTransportperc))
                            .addComponent(jTextFieldgrosssalary, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldhouse, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldHouseperc))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldbsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldMedicalperc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldbsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMedicalperc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldhouse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldHouseperc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldtransport, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTransportperc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldgrosssalary, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSearchActionPerformed
        
         try{
        String sqlSearch="select * from employee_info where 	id = '"+jComboBoxSearch.getSelectedItem()+"'";
            prepStmt = con.prepareStatement(sqlSearch);
            res=prepStmt.executeQuery();
            
            while(res.next())
                {
                    
                    String Name = res.getString("name");
                    String Desig = res.getString("designation");
                    
                    
                    
                   jTextFieldempname.setText(Name);
                   jTextFieldDesig.setText(Desig);
                    
            
        }
           
            
          
        }
        catch(SQLException e){
            
           
        }
        
        
        try{
            
            
            
            
            String sqlSearch = "select employee_info.id,employee_info.name,employee_info.designation,employee_salary.basic_salary,employee_salary.medical_allowance,employee_salary.medicalperc,employee_salary.house_rent,employee_salary.houseperc,employee_salary.transport_al,employee_salary.transportperc,employee_salary.gross_salary,employee_salary.Sal_Date from employee_info,employee_salary where employee_info.id=employee_salary.id AND employee_info.id = '"+jComboBoxSearch.getSelectedItem().toString()+"' ";
            
            prepStmt = con.prepareStatement(sqlSearch);
            res=prepStmt.executeQuery();
            
            while(res.next())
                {
                    
                    String Name = res.getString("employee_info.name");
                    String Deg = res.getString("employee_info.designation");
                    String BS = res.getString("employee_salary.basic_salary");
                    String MA = res.getString("employee_salary.medical_allowance");
                    String MAP = res.getString("employee_salary.medicalperc");
                    String HR = res.getString("employee_salary.house_rent");
                    String HRP=res.getString("employee_salary.houseperc");
                    String TA = res.getString("employee_salary.transport_al");
                    String TAP=res.getString("employee_salary.transportperc");
                    String GS = res.getString("employee_salary.gross_salary");
                    Date DD = res.getDate("employee_salary.Sal_Date");
                    
                    
                    
                    jTextFieldempname.setText(Name);
                    jTextFieldDesig.setText(Deg);
                    jTextFieldbsalary.setText(BS);
                    jTextFieldmedical.setText(MA);
                    jTextFieldMedicalperc.setText(MAP);
                    jTextFieldhouse.setText(HR);
                    jTextFieldHouseperc.setText(HRP);
                    jTextFieldtransport.setText(TA);
                    jTextFieldTransportperc.setText(TAP);
                    jTextFieldgrosssalary.setText(GS);
                    jDateChooser1.setDate(DD);
                    
               
        }
           
            
          
        }
        catch(SQLException e){
            
           
        }
    }//GEN-LAST:event_jComboBoxSearchActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        
        java.sql.Date Sald = new java.sql.Date(jDateChooser1.getDate().getTime());
        
        
         try{
            
            
            String sqlQry="insert into employee_salary(id,basic_salary,medical_allowance,medicalperc,house_rent,houseperc,transport_al,transportperc,gross_salary,Sal_Date) values(?,?,?,?,?,?,?,?,?,?)";
            
            prepStmt = con.prepareStatement(sqlQry);

                        prepStmt.setString(1, (String) jComboBoxSearch.getSelectedItem());
                        prepStmt.setString(2, jTextFieldbsalary.getText());
                        prepStmt.setString(3, jTextFieldmedical.getText());
                        prepStmt.setString(4, jTextFieldMedicalperc.getText());
                        prepStmt.setString(5, jTextFieldhouse.getText());
                        prepStmt.setString(6, jTextFieldHouseperc.getText());
                        prepStmt.setString(7, jTextFieldtransport.getText());
                        prepStmt.setString(8, jTextFieldTransportperc.getText());
                        prepStmt.setString(9, jTextFieldgrosssalary.getText());
                        prepStmt.setDate(10, Sald);
                        
                        
                       
                       int i= prepStmt.executeUpdate();
                       
                       if(i>0){
                           JOptionPane.showMessageDialog(this, "Saved");
                       }
            
        }catch(SQLException e){
            
        }
        
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        
        int msg = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Are You Sure to Exit?","Warning",msg);
        if (result==0)
        {
        System.exit(0);
        }
        else
        {
            System.out.println(" ");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        jComboBoxSearch.setSelectedItem("Select ID");
        jTextFieldempname.setText(null);
        jTextFieldDesig.setText(null);
        jTextFieldbsalary.setText("0");
        jTextFieldmedical.setText("0");
        jTextFieldhouse.setText("0");
        jTextFieldtransport.setText("0");
        jTextFieldgrosssalary.setText("0");
        jTextFieldSearch.setText(null);
        jTextFieldMedicalperc.setText("0");
        jTextFieldHouseperc.setText("0");
        jTextFieldTransportperc.setText("0");
        
        jDateChooser1.setDate(now);
        
        
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        int msg = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Are You Sure to Update?","Warning",msg);
        if (result==0)
        {
        
            
         java.sql.Date paytime=new java.sql.Date(jDateChooser1.getDate().getTime());
            
        try{
            
            
            
            
            String sqlQry="UPDATE employee_salary SET basic_salary= ?,medical_allowance = ?, medicalperc = ?, house_rent = ?, houseperc = ?, transport_al = ?, transportperc= ?, gross_salary = ?, Sal_Date=? WHERE id = ?";
            
            prepStmt = con.prepareStatement(sqlQry);

                        
                        prepStmt.setString(1, jTextFieldbsalary.getText());
                        prepStmt.setString(2, jTextFieldmedical.getText());
                        prepStmt.setString(3, jTextFieldMedicalperc.getText());
                        prepStmt.setString(4, jTextFieldhouse.getText());
                        prepStmt.setString(5, jTextFieldHouseperc.getText());
                        prepStmt.setString(6, jTextFieldtransport.getText());
                        prepStmt.setString(7, jTextFieldTransportperc.getText());
                        prepStmt.setString(8, jTextFieldgrosssalary.getText());
                        prepStmt.setDate(9, paytime);
                        prepStmt.setString(10, (String) jComboBoxSearch.getSelectedItem());
                        
                        
                        
                       
                       int i= prepStmt.executeUpdate();
                       
                       if(i>0){
                           JOptionPane.showMessageDialog(this, "DATABAE UPDATED");
                       }
            
        }catch(SQLException e){
            
        }
        }
        else
        {
            System.out.println(" ");
        }
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        
        
        int test = 1;
        
        try{
            String SearchID = jTextFieldSearch.getText();
            
            String sqlSearch="select * from employee_salary where id = '"+SearchID+"'";
            prepStmt = con.prepareStatement(sqlSearch);
            res=prepStmt.executeQuery();
            
            while(res.next())
                {
                    
                    String ID = res.getString("id");
                    String B_Salary = res.getString("basic_salary");
                    String Medical_Al = res.getString("medical_allowance");
                    String Medical_Al_PER = res.getString("medicalperc");
                     
                    String House_Rent = res.getString("house_rent");
                    String House_Rent_PER = res.getString("houseperc");
                    
                    
                    String Transpoort = res.getString("transport_al");
                    String Transpoort_PER = res.getString("transportperc");
                    
                    String Gross_Salary = res.getString("gross_salary");
                    
                    Date pay=res.getDate("Sal_Date");
                    
                    
                    
                    
                    
                    jComboBoxSearch.setSelectedItem(ID);
                    jTextFieldbsalary.setText(B_Salary);
                    jTextFieldmedical.setText(Medical_Al);
                    jTextFieldMedicalperc.setText(Medical_Al_PER);
                    
                    jTextFieldhouse.setText(House_Rent);
                    jTextFieldHouseperc.setText(House_Rent_PER);
                    
                    
                    jTextFieldtransport.setText(Transpoort);
                    jTextFieldTransportperc.setText(Transpoort_PER);
                    jTextFieldgrosssalary.setText(Gross_Salary);
                     jDateChooser1.setDate(pay);
                    
                    test=0;
                    JOptionPane.showMessageDialog(this, "Weldone"+"\n"+"Searching Completed");
                    
                    break;
            
        }
           
            
          if(test==1){
                JOptionPane.showMessageDialog(this, "Error Occurred!!!"+"\n"+"\n"+"Data Not Found"+"\n"+"Please Try Again Later");
            }  
            
        }
        catch(SQLException e){
            
           
        }
        
        
        
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchActionPerformed
        
        
        int test = 1;
        
        try{
            String SearchID = jTextFieldSearch.getText();
            
            String sqlSearch="select * from employee_salary where id = '"+SearchID+"'";
            prepStmt = con.prepareStatement(sqlSearch);
            res=prepStmt.executeQuery();
            
            while(res.next())
                {
                    
                    String ID = res.getString("id");
                    String B_Salary = res.getString("basic_salary");
                    String Medical_Al = res.getString("medical_allowance");
                    String Medical_Al_PER = res.getString("medicalperc");
                     
                    String House_Rent = res.getString("house_rent");
                    String House_Rent_PER = res.getString("houseperc");
                    
                    
                    String Transpoort = res.getString("transport_al");
                    String Transpoort_PER = res.getString("transportperc");
                    
                    String Gross_Salary = res.getString("gross_salary");
                    
                    Date pay=res.getDate("Sal_Date");
                    
                    
                    
                    
                    
                    jComboBoxSearch.setSelectedItem(ID);
                    jTextFieldbsalary.setText(B_Salary);
                    jTextFieldmedical.setText(Medical_Al);
                    jTextFieldMedicalperc.setText(Medical_Al_PER);
                    
                    jTextFieldhouse.setText(House_Rent);
                    jTextFieldHouseperc.setText(House_Rent_PER);
                    
                    
                    jTextFieldtransport.setText(Transpoort);
                    jTextFieldTransportperc.setText(Transpoort_PER);
                    jTextFieldgrosssalary.setText(Gross_Salary);
                     jDateChooser1.setDate(pay);
                    
                    test=0;
                    JOptionPane.showMessageDialog(this, "Weldone"+"\n"+"Searching Completed");
                    
                    break;
            
        }
           
            
          if(test==1){
                JOptionPane.showMessageDialog(this, "Error Occurred!!!"+"\n"+"\n"+"Data Not Found"+"\n"+"Please Try Again Later");
            }  
            
        }
        catch(SQLException e){
            
           
        }
    }//GEN-LAST:event_jTextFieldSearchActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        
        int msg=JOptionPane.YES_NO_OPTION;
        
        
       int result= JOptionPane.showConfirmDialog(this, "Are You Sure to Delete?","Warning",msg);
        if(result==0){
            System.out.println("Yes Option");
        try{
            String sqlQry="DELETE from employee_salary WHERE id= ?";
            
             prepStmt = con.prepareStatement(sqlQry);
            
            prepStmt.setString(1, (String) jComboBoxSearch.getSelectedItem());
                       
                       int i= prepStmt.executeUpdate();
                       
                       if(i>0){
                           JOptionPane.showMessageDialog(this, "RECORD DELETED");
                       }
            
        }catch(SQLException | HeadlessException e)
        {
            
        }
        
        jComboBoxSearch.setSelectedItem("Select ID");
        jTextFieldempname.setText(null);
        jTextFieldDesig.setText(null);
        jTextFieldbsalary.setText(null);
        jTextFieldmedical.setText(null);
        jTextFieldhouse.setText(null);
        jTextFieldtransport.setText(null);
        jTextFieldgrosssalary.setText(null);
        jTextFieldSearch.setText(null);
        
       
        }else{
           System.out.println("No Option");
        }
       
        
        
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jTextFieldtransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtransportActionPerformed
       
        try{
            
     
        double grosssalary=Double.parseDouble(jTextFieldbsalary.getText())+Double.parseDouble(jTextFieldmedical.getText())+Double.parseDouble(jTextFieldhouse.getText())+Double.parseDouble(jTextFieldtransport.getText());
        String total=Double.toString(grosssalary);
        
        jTextFieldgrosssalary.setText(total);
        }catch(Exception e)
        {
            System.out.println("Error==>"+e);
        }
    }//GEN-LAST:event_jTextFieldtransportActionPerformed

    private void jTextFieldgrosssalaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldgrosssalaryMouseClicked
        double grosssalary=Double.parseDouble(jTextFieldbsalary.getText())+Double.parseDouble(jTextFieldmedical.getText())+Double.parseDouble(jTextFieldhouse.getText())+Double.parseDouble(jTextFieldtransport.getText());
        String total=Double.toString(grosssalary);
        
        jTextFieldgrosssalary.setText(total);
        
        
    }//GEN-LAST:event_jTextFieldgrosssalaryMouseClicked

    private void jTextFieldMedicalpercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMedicalpercActionPerformed
        try{
            
            
        double medical = Double.parseDouble(jTextFieldMedicalperc.getText());
        double basicsalary=Double.parseDouble(jTextFieldbsalary.getText());
        double all = (basicsalary*medical/100);
        String mediall=Double.toString(all);
        jTextFieldmedical.setText(mediall);
        
        double grosssalary=Double.parseDouble(jTextFieldbsalary.getText())+Double.parseDouble(jTextFieldmedical.getText())+Double.parseDouble(jTextFieldhouse.getText())+Double.parseDouble(jTextFieldtransport.getText());
        String total=Double.toString(grosssalary);
        
        jTextFieldgrosssalary.setText(total);
        
        
        
        }catch(Exception e)
        {
            System.out.println("Error ==> "+e);
        }
    }//GEN-LAST:event_jTextFieldMedicalpercActionPerformed

    private void jTextFieldHousepercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHousepercActionPerformed
        try{
        double medical = Double.parseDouble(jTextFieldHouseperc.getText());
        double basicsalary=Double.parseDouble(jTextFieldbsalary.getText());
        double all = (basicsalary*medical/100);
        String mediall=Double.toString(all);
        jTextFieldhouse.setText(mediall);
        
        
        double grosssalary=Double.parseDouble(jTextFieldbsalary.getText())+Double.parseDouble(jTextFieldmedical.getText())+Double.parseDouble(jTextFieldhouse.getText())+Double.parseDouble(jTextFieldtransport.getText());
        String total=Double.toString(grosssalary);
        
        jTextFieldgrosssalary.setText(total);
        
        }catch(Exception e)
        {
            System.out.println("Error ==> "+e);
        }
    }//GEN-LAST:event_jTextFieldHousepercActionPerformed

    private void jTextFieldTransportpercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTransportpercActionPerformed
       try{
        double medical = Double.parseDouble(jTextFieldTransportperc.getText());
        double basicsalary=Double.parseDouble(jTextFieldbsalary.getText());
        double all = (basicsalary*medical/100);
        String mediall=Double.toString(all);
        jTextFieldtransport.setText(mediall);
        
        
        double grosssalary=Double.parseDouble(jTextFieldbsalary.getText())+Double.parseDouble(jTextFieldmedical.getText())+Double.parseDouble(jTextFieldhouse.getText())+Double.parseDouble(jTextFieldtransport.getText());
        String total=Double.toString(grosssalary);
        
        jTextFieldgrosssalary.setText(total);
        
       }catch(Exception e)
       {
           System.out.println("Error : "+e);
       }
        
        
    }//GEN-LAST:event_jTextFieldTransportpercActionPerformed

    private void jTextFieldmedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmedicalActionPerformed
        
    }//GEN-LAST:event_jTextFieldmedicalActionPerformed

    private void jTextFieldgrosssalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldgrosssalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldgrosssalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Salary_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Salary_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JComboBox jComboBoxSearch;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldDesig;
    private javax.swing.JTextField jTextFieldHouseperc;
    private javax.swing.JTextField jTextFieldMedicalperc;
    private javax.swing.JTextField jTextFieldSearch;
    private javax.swing.JTextField jTextFieldTransportperc;
    private javax.swing.JTextField jTextFieldbsalary;
    private javax.swing.JTextField jTextFieldempname;
    private javax.swing.JTextField jTextFieldgrosssalary;
    private javax.swing.JTextField jTextFieldhouse;
    private javax.swing.JTextField jTextFieldmedical;
    private javax.swing.JTextField jTextFieldtransport;
    // End of variables declaration//GEN-END:variables
}
